# Generated by Django 3.2.15 on 2022-09-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='description',
            field=models.TextField(max_length=100),
        ),
    ]
